<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxCart
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div data-bind="scope: 'message'" data-role="quickview-message" class="bss-notice messages">
    <div class="message-notice notice message">
        <div class="first-data" data-bind="text: getMessageInCart()"></div>
    </div>
</div>
<script type="text/x-magento-init">
{
	"[data-role=quickview-message]": {
		"Magento_Ui/js/core/app": {
			"components": {
				"message": {
					"component":"Bss_AjaxCart/js/message"
				}
			}
		}
	}
}
</script>
