<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_Walletsystem
 * @author Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
$url = $block->getajaxUrl();
$grandTotal = $block->getGrandTotal();
$this->helper('Webkul\Walletsystem\Helper\Data')->checkWalletproductWithOtherProduct();
?>
<?php
$formData = [
    'grandtotal'   => $grandTotal,
    'ajaxurl'       => $url,
    'wkshippingmethod'    =>  '#shipping-method-buttons-container button.continue'
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Wkwalletsystem": <?php /* @escapeNotVerified */echo $serializedFormData; ?>
        }
    }
</script>