<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Downloadable\Block\Sales\Order\Item\Renderer\Downloadable */
?>
<?php $_item = $block->getItem();
$product= $_item->getProduct();
$id= $_item->getId();
$orderItem=$block->getItem()->getOrderItem();
$fileName=$orderItem->getBuyRequest()->getImageHtml();
$fileNameCheck=$fileName;
$personalized=$this->helper('Milople\Personalizedcool\Helper\Product\View\Personalized');
$fileName=$personalized->getImageMediaUrl($fileName);
$status=$personalized->getConfig('personalizedcool/license_status_group/status'); 
$counter = 1;
 ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        
      <?php if($fileNameCheck!='' && $status): ?>
                         <a class="preview-link" data-modal="open-<?php echo $id ?>">
								<?php echo $block->escapeHtml(__('PREVIEW')); ?>
							</a>
							<div class="modal-wrapper" data-modal="wrapper-<?php echo $id ?>">
								<div class="modal-content">
									<a class="close-modal" data-modal="close-<?php echo $id ?>">&times;</a>
									<div class="text">
										<div class="callbacks_container">
											<ul class="rslides" id="productpersonalized-<?php echo $id ?>">
												<?php foreach ($fileName as $image) {
													if($counter % 2 != 0 && $image!="blank") {
												?>
													<li>
														<img src=<?php echo $image ?> />
													</li>   
											   <?php } $counter++; } ?>
											</ul>
										</div>
									</div>
								</div>
							</div>
      <?php endif; ?>
      </br>
      <script>
require(["jquery"], function (jQuery) {
	<?php if($fileNameCheck!='' ): ?>
        var jQuery = jQuery.noConflict();
		jQuery(function () {
		jQuery("#productpersonalized-<?php echo $_item->getId() ?>").responsiveSlides({
			auto: false,
			pager: false,
			nav: true,
			speed: 500,
			namespace: "callbacks",
			before: function () {
			},
			after: function () {
			}
		});

		var Modal = (function() {
			var modalOpen = document.querySelector('[data-modal="open-<?php echo $_item->getId() ?>"]'),
			modalClose = document.querySelector('[data-modal="close-<?php echo $_item->getId() ?>"]'),
			modalWrapper = document.querySelector('[data-modal="wrapper-<?php echo $_item->getId() ?>"]');

			return {
				init: function() {
					this.open();
					this.close();
				},

				open: function() {
					modalOpen.onclick = function(e) {
						e.preventDefault;
						modalWrapper.classList.add("modal-opened");
					}
				},

				close: function() {
					modalClose.onclick = function(e) {
						e.preventDefault;
						modalWrapper.classList.remove("modal-opened");
					}
				}
			}
		}());
		Modal.init();
	});
	<?php endif; ?>
});
</script>
      
      <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options links">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                            <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                        <dd><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* downloadable */ ?>
        <?php if ($links = $block->getLinks()): ?>
            <dl class="item-options links">
                <dt><?php /* @escapeNotVerified */ echo $block->getLinksTitle() ?></dt>
                <?php foreach ($links->getPurchasedItems() as $link): ?>
                    <dd><?php echo $block->escapeHtml($link->getLinkTitle()); ?></dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* EOF downloadable */ ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty Invoiced')); ?>">
        <span class="qty summary" data-label="<?php echo $block->escapeHtml(__('Qty Invoiced')); ?>"><?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?></span>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
