<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CancelOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile
/**
 * History template
 *
 * @var $block \Magento\Sales\Block\Order\Recent
 */
?>
<?php $_orders = $block->getOrders(); ?>
<?php /* @escapeNotVerified */ echo $block->getChildHtml('info');?>
<?php if ($_orders && !empty($_orders)) : ?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
        <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                <?php /* @noEscape */ echo $block->getChildHtml('extra.column.header');?>
                <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Ship To') ?></th>
                <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php $orderIdCurrent = ""; ?>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id">
                        <?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date">
                        <?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?>
                    </td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?php /* @noEscape */ echo $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping">
                        <?php echo $_order->getShippingAddress() ?
                            $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total">
                        <?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status">
                        <?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>"
                            class="action view">
                            <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                        </a>
                        <?php $reorderHelper = $this->helper(\Magento\Sales\Helper\Reorder::class); ?>
                        <?php if ($reorderHelper->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
                            </a>
                        <?php endif ?>

                        <?php if ($_order->getState() == "new" || $_order->getState() == "pending_payment") : ?>
                            <a href="#"
                                class="cd-popup-trigger"
                                data-order-id="<?php /* @escapeNotVerified */
                                                    echo $_order->getIncrementId(); ?>">
                                <?php /* @escapeNotVerified */ echo $block->getChildHtml('cancel_link'); ?>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php /* @escapeNotVerified */ echo $block->getChildHtml('cancel_popup'); ?>
</div>

<?php if ($block->getPagerHtml()) : ?>
    <div class="order-products-toolbar toolbar bottom">
        <?php /* @escapeNotVerified */ echo $block->getPagerHtml(); ?>
    </div>
<?php endif ?>

<?php else : ?>
    <div class="message info empty">
        <span><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?></span>
    </div>
<?php endif ?>
